### ISSUE TITLE
livechat diagnostic fails prosody

### ISSUE THREAD

**Issue by 01123581321345589144233** [JohnXLivingston/peertube-plugin-livechat#102]
Hi i have installed after this wiki https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/README.md
prosody. Livechat is installed via peertube. I have checket the api url domain.com/plugins/livechat/5.7.0/router/api and it says 404.
My diag fails with:
    Starting tests: OK
    Browser: OK
    Backend connection: OK
    Webchat activated on videos: OK
        Chat will open automatically
        Displaying «open in new window» button
        Chat can be enabled on live videos.
    Webchat type: OK
        Using builtin Prosody
    Builtin Prosody and ConverseJS: KO
        The working dir is: /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
        Prosody will run on port '52800'
        Prosody will use https://domain.com/plugins/livechat/5.7.0/router/api/ as base uri from api calls
        Prosody modules path will be '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
        Prosody rooms will be grouped by 'video'.
        By default, room content will be archived.
        Room content will be saved for '1w'
        The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
        Prosody configuration file content is correct.
        Pid file /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
        Prosodyctl status: Prosody is running with PID 9423
        The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
        Prosody configuration file content is correct.
        Prosody version is 0.10.0
        Error when calling Prosody test api (test-peertube-prosody): HTTPError: Response code 404 (Not Found)

**Comment by JohnXLivingston** [comment]
Is this a docker installation?

Can you try this: in the plugin settings, at the bottom, there is a setting «Peertube url for API calls». Try the value «[http://127.0.0.1:9000»](http://127.0.0.1:9000%C2%BB) (assuming peertube is listening on port 9000).
You can also try «[http://localhost:9000»](http://localhost:9000%C2%BB).

**Comment by 01123581321345589144233** [comment]
Builtin Prosody and ConverseJS: KO

    The working dir is: /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
    Prosody will run on port '52800'
    Prosody will use http://127.0.0.1:9000/plugins/livechat/5.7.0/router/api/ as base uri from api calls
    Prosody modules path will be '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
    Prosody rooms will be grouped by 'video'.
    By default, room content will be archived.
    Room content will be saved for '1w'
    The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
    Prosody configuration file content is correct.
    Pid file /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
    Prosodyctl status: Prosody is running with PID 19259
    The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
    Prosody configuration file content is correct.
    Prosody version is 0.10.0
    Error when calling Prosody test api (test-peertube-prosody): HTTPError: Response code 404 (Not Found)

**Comment by JohnXLivingston** [comment]
I see `Prosody version is 0.10.0`.
Prosody 0.10.0 was released in 2017. Current version is 0.12 (or 0.11.9 on Debian stable for example). Can you try to update your Prosody version? Could be related.

**Comment by 01123581321345589144233** [comment]
Builtin Prosody and ConverseJS: KO
        The working dir is: /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
        Prosody will run on port '52800'
        Prosody will use http://127.0.0.1:9000/plugins/livechat/5.7.0/router/api/ as base uri from api calls
        Prosody modules path will be '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
        Prosody rooms will be grouped by 'video'.
        By default, room content will be archived.
        Room content will be saved for '1w'
        The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
        Prosody configuration file content is correct.
        Pid file /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
        Prosodyctl status: ************************** Prosody was unable to find lua-unbound This package can be obtained in the following ways: Debian/Ubuntu | sudo apt install lua-unbound luarocks | luarocks install luaunbound Source | https://www.zash.se/luaunbound.html Old DNS resolver library will be used More help can be found on our website, at https://prosody.im/doc/depends ************************** general warn Lua 5.1 has several issues and support is being phased out, consider upgrading certmanager error Error indexing certificate directory /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: cannot open /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: No such file or directory Prosody is running with PID 19259
        The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
        Prosody configuration file content is correct.
        Prosody version is 0.12.1
        Error when calling Prosody test api (test-peertube-prosody): HTTPError: Response code 404 (Not Found)

**Comment by 01123581321345589144233** [comment]
after restart peertube:

Builtin Prosody and ConverseJS: OK

    The working dir is: /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
    Prosody will run on port '52800'
    Prosody will use http://127.0.0.1:9000/plugins/livechat/5.7.0/router/api/ as base uri from api calls
    Prosody modules path will be '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
    Prosody rooms will be grouped by 'video'.
    By default, room content will be archived.
    Room content will be saved for '1w'
    The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
    Prosody configuration file content is correct.
    Pid file /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
    Prosodyctl status: ************************** Prosody was unable to find lua-unbound This package can be obtained in the following ways: Debian/Ubuntu | sudo apt install lua-unbound luarocks | luarocks install luaunbound Source | https://www.zash.se/luaunbound.html Old DNS resolver library will be used More help can be found on our website, at https://prosody.im/doc/depends ************************** general warn Lua 5.1 has several issues and support is being phased out, consider upgrading certmanager error Error indexing certificate directory /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: cannot open /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/certs: No such file or directory Prosody is running with PID 24401
    The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
    Prosody configuration file content is correct.
    Prosody version is 0.12.1
    API Peertube -> Prosody is OK
    API Prosody -> Peertube is OK

**Comment by 01123581321345589144233** [comment]
update prosody an debian and ubuntu:
# echo deb http://packages.prosody.im/debian $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/prosody.list
# sudo wget https://prosody.im/files/prosody-debian-packages.key -O/etc/apt/trusted.gpg.d/prosody.gpg
# sudo apt update
# sudo apt install prosody
# apt list -a prosody
restart peertube and prosody

**Comment by 01123581321345589144233** [comment]
:-)

**Comment by JohnXLivingston** [comment]
Great.
For the record, Prosody is officially packaged for debian. You don't have to add prosody repository. What's your debian version?

**Comment by 01123581321345589144233** [comment]
ubuntu 18
