### ISSUE TITLE
slow chat mode

### ISSUE THREAD

**Issue by animegrafmays** [JohnXLivingston/peertube-plugin-livechat#105]
**Is your feature request related to a problem? Please describe.**
prosody seems to lock up when too many people are speaking or spamming chat

**Describe the solution you'd like**
prosody has built-in [rate limiting](https://modules.prosody.im/mod_muc_limits), this could be implemented in this plugin's prosody deployment configuration and perhaps be toggleable in the plugin settings (or in the moderation panel) 

**Describe alternatives you've considered**
replacing prosody with ejabberd or similar option

**Additional context**
Issue #95

**Comment by JohnXLivingston** [comment]
Replaced by: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/192

**Comment by animegrafmays** [comment]
this isn't resolved btw it still happens, regardless if people are chatting or not

**Comment by JohnXLivingston** [comment]
> this isn't resolved btw it still happens, regardless if people are chatting or not

I know. I just created multiple issues for a better project management.
I finally found a sponsor, so I can work on scalability issues. See this tag for all related issues: https://github.com/JohnXLivingston/peertube-plugin-livechat/labels/Type%3A%20Scalability
