### ISSUE TITLE
TK2210-0094. XMPP clients connections

### ISSUE THREAD

**Issue by JohnXLivingston** [JohnXLivingston/peertube-plugin-livechat#114]
Peertube administrators should be enable to allow to connect to the livechat using a XMPP client. There are several advantages to enable such usages. For example, moderation will be simpler using a XMPP client, than using the web interface. Or you can use moderation bots, and other advanced tools. But this will require some setup on the server. It can’t be enabled only by using the Peertube web interface. This task consist to offer the choice to open such connection in the Peertube interface, and document the additional steps than admins have to do on the server.

- [x] Add settings
- [x] Add documentation

**Comment by poVoq** [comment]
You could put this in front: https://github.com/moparisthebest/xmpp-proxy to allow normal 5222 client connections I think.

**Comment by JohnXLivingston** [comment]
Thanks @poVoq . I see this allow Websocket S2S ?! I was looking for such a thing for another feature: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/112

**Comment by moparisthebest** [comment]
Hi! If you have any questions about or need any help with xmpp-proxy feel free to let me know!

It does indeed support S2S over WebSocket, but it might be the only thing to support it so far, the spec is pretty new. :)

**Comment by JohnXLivingston** [comment]
@poVoq , I was in a hurry yesterday, and I read your message too quickly. I have constraints: I must use Peertube (written in NodeJS) as Proxy. So, as far as I know, I can't use a Rust library as a proxy.
My constraints are explained in french here: https://www.john-livingston.fr/foss/article/plugin-de-tchat-peertube-retour-rapide-sur-un-test-de-montee-en-charge (english translation will soon be available).

@moparisthebest , your code can still help me!
mod_s2s_outgoing_proxy.lua will be helpfull, and I can try to translate your code to NodeJS.
To be continued :)

**Comment by JohnXLivingston** [comment]
English translation of the article mentioned in the previous comment:
https://www.john-livingston.fr/foss/article/peertube-chat-plugin-quick-feedbacks-about-a-live-stress-test

**Comment by moparisthebest** [comment]
Thanks for the English, translation, if I understand that right you could put xmpp-proxy in the same AppImage as prosody and then use an off the shelf plain TCP or WebSocket node proxy to get to it?

**Comment by JohnXLivingston** [comment]
> Thanks for the English translation, if I understand that right you could put xmpp-proxy in the same AppImage as prosody and then use an off the shelf plain TCP or WebSocket node proxy to get to it?

Maybe. But might be overkill. Need some thinking. This issue is planed to be done in 2nd 2023 quarter, i'll keep you in touch then.

**Comment by JohnXLivingston** [comment]
Feature implemented, and documented. Will be available on next release (no date announced for now)
