### ISSUE TITLE
Feature Request: Random color for nicknames

### ISSUE THREAD

**Issue by JohnXLivingston** [JohnXLivingston/peertube-plugin-livechat#143]
For now, all nicknames have the same color. For a better readability, it will be really usefull to have different colors for each user.
There is a XEP for «[consistent color generation](https://xmpp.org/extensions/xep-0392.html)».

We will implement this in ConverseJS (as a plugin, or upstream). An issue is open in ConverseJS: https://github.com/conversejs/converse.js/issues/1349

Reference: NlNet-task-15

**Comment by mwild1** [comment]
Relatedly, there is [XEP-0392](https://xmpp.org/extensions/xep-0392.html) with an algorithm you can use to reproducibly calculate the same colour for a nickname (which helps with visual identification). See also [this web tool](https://matthewwild.co.uk/projects/xep0392-web/) (and feel free to borrow the code).

**Comment by JohnXLivingston** [comment]
Thanks @mwild1 !

**Comment by JohnXLivingston** [comment]
@jcbrand, would you be interested to add this XEP in ConverseJS?
It could be an option, disabled by default.

**Comment by jcbrand** [comment]
We have a ticket for it:
https://github.com/conversejs/converse.js/issues/1349

Would be nice to have but there's no concrete timeline/roadmap for it.

**Comment by JohnXLivingston** [comment]
Here is the result when implementing XEP-0392:

![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/cc470486-997f-43ae-b587-0baffa0b3da1)

And in dark mode:

![Uploading image.png…]()
