### ISSUE TITLE
/clear does not work anymore

### ISSUE THREAD

**Issue by EkkiBrue** [JohnXLivingston/peertube-plugin-livechat#149]
Version 6.1.0

https://video.medienzentrum-harburg.de/plugins/livechat/6.1.0/router/webchat/room/e89079bc-62e3-4fee-a40d-2a47d5293db7

Logged in as admin in peertube.

Livechat does not allow the admin to /clear the chat input.
After submitting /clear the screen gets flushed but: Pressing f5 and reloading the site shows the old content.

It was working in 6.0 before.

**Comment by JohnXLivingston** [comment]
Hello,

/clear only clears for the current user. And when refreshing, it will indeed reload messages from server.

To fully clear a room, you will have to delete it:
- open the menu on the top right
- click on «details»
- copy the room address (in your case `xmpp:e89079bc-62e3-4fee-a40d-2a47d5293db7@room.video.medienzentrum-harburg.de?join`
- open the menu on the top right
- click on «destroy»
- in the popup, you will have to paste the room name to confirm
- once the room destroyed, just refresh the page: the room will be re-created automatically

I know this is not simple. I will add buttons to do this more easily in a future version

**Comment by JohnXLivingston** [comment]
Is this response good for you? If so, you can close the issue.

**Comment by JohnXLivingston** [comment]
I'm closing the issue, as it seems you managed to clear the chat (the one you mentioned in your first message)

**Comment by JohnXLivingston** [comment]
I'm closing the issue, as it seems you managed to clear the chat (the one you mentioned in your first message)

**Comment by EkkiBrue** [comment]
Thank you John!!!! I was busy the last days so I couldn´t reply.... Surething that fixed my issue.
