### ISSUE TITLE
Openfire connection not working

### ISSUE THREAD

**Issue by Alterak** [JohnXLivingston/peertube-plugin-livechat#16]
**Describe the bug**
I failed to configure the Prosody server, But I successfully installed the Openfire server and activated an anonymous connection to the server. Programs (for example Jabber or Wime or Pidgin) connect to the server successfully! But the Peertube plugin does not want to connect to the server.

**To Reproduce**
After installing the server, I activated anonymous connection. I created a permanent room with the address chat@conference.chat.ustim.ru.
In the plugin settings, I specified the server address and also added a line with the address of the public conference chat@conference.chat.ustim.ru.
Plugin won't connect

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/11453567/110469981-5a902c80-80eb-11eb-9298-6217b6d12413.png)
![Screenshot_2](https://user-images.githubusercontent.com/11453567/110470730-4436a080-80ec-11eb-8fc5-4ff44384b112.png)
![Screenshot_3](https://user-images.githubusercontent.com/11453567/110470736-47ca2780-80ec-11eb-8579-eb0afaf7c8a7.png)
![Screenshot_4](https://user-images.githubusercontent.com/11453567/110470752-4c8edb80-80ec-11eb-8fdb-ba701a4d9031.png)

**Comment by JohnXLivingston** [comment]
Can you give me the link to the video so that I can debug?

**Comment by JohnXLivingston** [comment]
There are some configuration missing. You have to provide a BOSH service (also known as http-bind) and/or websocket service, and paste their url in «BOSH uri» and/or «WS uri».

**Comment by Alterak** [comment]
> There are some configuration missing. You have to provide a BOSH service (also known as http-bind) and/or websocket service, and paste their url in «BOSH uri» and/or «WS uri».

Here is a link to the video ... Now I will try to find BOSH uri

**Comment by Alterak** [comment]
I am new to XMPP server settings, but it seems I found these settings, they were activated
![Screenshot_5](https://user-images.githubusercontent.com/11453567/110472856-f2434a00-80ee-11eb-9c20-2829e6945df7.png)

**Comment by Alterak** [comment]
I added the address http://chat.ustim.ru:7070/http-bind/ in the plugin settings, in the section ** Builtin webchat: BOSH uri **

Now the chat frame has changed a bit, but there is still no connection- (

**Comment by JohnXLivingston** [comment]
That should be correct. Have you a firewall? Have you open ports 7070 and 7443?

It is not mandatory, but you should use https for the bosh service:  https://chat.ustim.ru:7443/http-bind/  (hope Openfire has a valid certificate)

**Comment by JohnXLivingston** [comment]
When I try to open these links in my browser, I have no response

**Comment by JohnXLivingston** [comment]
>  An error is displayed

I don't know if the error is relevant, it depends on the http-bind server. Prosody displays a page like this one: https://peertube.im.yiny.org/http-bind . I don't know if openfire does that or not.

**Comment by Alterak** [comment]
> If it is too complicated to make openfire work, i'm going to write a simple tutorial to add Prosody directly on the peertube server, with very few configuration. I will try to write it this week.

I'll be waiting for you to complete your instructions. Thank you for the work done!

**Comment by JohnXLivingston** [comment]
Ok. You can subscribe to this repository modifications to receive a notification when I commit the tutorial.

**Comment by JohnXLivingston** [comment]
@Alterak  here is a first draft for the prosody tutorial: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/tutorials/prosody.md

**Comment by JohnXLivingston** [comment]
Closing (see https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/20)
