### ISSUE TITLE
WebSocket Mystery, Assistance tracking down the source is appreciated.

### ISSUE THREAD

**Issue by davidleebooth** [JohnXLivingston/peertube-plugin-livechat#188]
Hi there, I am on PeerTube 5.1.0 with the latest version of the livechat plugin, installed via Docker official and using Caprover as an application manager. I am encountering a WebSocket not found error in my browser inspector and in need of assistance tracking it down and a solution with the appropriate party.

The odd behaviors I get in tandem with this error are livestreams do not broadcast on federated instances instead spinning, and watching via a mobile chrome app or on browser has the same result while on my own instance. the error here is:

WebSocket connection to 'wss://davbot.media/socket.io/?accessToken=65aec0e7b6ed757ec9c654d80a450b9d1cada282&EIO=4&transport=websocket&sid=4kjst7ApPjMU6cXyAAAx' failed: 
doOpen	@	360.e3d42fe8da2a6e0a.js:1

in the update instructions for peertube 5 there are some NGINX values to add regarding websockets. I have attempted entering them into caprovers custom NGINX in a myraid of ways, even replacing the caprover NGINX with the suggested from PeerTube with no change. I had ticketed caprover install requesting assistance and providing information which was then closed and moved to the specific app installation forum, my follow up has yet to be acknowledged:

https://github.com/caprover/one-click-apps/pull/897

So I am unsure if this is a Peertube Websockets/caprover NGINX issue, or the Streaming Plugin/caprover NGINX. or possibly solely a Caprover NGINX issue. Below is the NGINX values that are in PeerTube default install. If anyone can help either rule out livestream plugin and narrow down my hunt or point out a solution that I am just blind to that would be greatly appreciated.

```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

    <%
    #I presume websocket from Peertube 5 will go here, I have just not been able to get a change in the error. https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
```

**Comment by JohnXLivingston** [comment]
Hello,

I don't know Caprover.
Your nginx configuration file seems to have multiple missing parts (regarding https://github.com/Chocobozzz/PeerTube/blob/develop/support/nginx/peertube )

### First solution: disable websocket in the plugin

You can disable Websocket in the plugin settings (there is a parameter in the plugin settings page).
This will make it work using the BOSH protocol. It is less efficient, but it will work.

But doing so, you won't be able to federate chats (this needs Websocket). This mean that remote user won't be able to connect to the chat from their remote instance. And you won't be able to join chat from other instances videos.

This could be a temporary workaround, waiting for a Caprover fix.

### Second solution: fix nginx conf

There are a lot of missing parts in this configuration file.
Once again, I don't know Caprover. Is there 2 nginx? One in front, using this template file, and one other?

This following part:

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;
```

must only apply on websocket locations. Here are the required locations:

* location /socket.io 
* location /tracker/socket {
* location ~ ^/plugins/[^/]+(/[^/]+)?/ws/

Here you apply it on location /

There are many other configuration issue in this template file. Missing locations, missing client_max_body_size customization depending on location, ...
You should ask for a complete refactoring of this template, based on the official Peertube conf file.

**Comment by JohnXLivingston** [comment]
Any update on this @davidleebooth ?

**Comment by JohnXLivingston** [comment]
Closing as no answer.
