### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Saddamus** [JohnXLivingston/peertube-plugin-livechat#23]
Not sure what i did wrong, but some files seem to be missing and can not find them on your repository:
![image](https://user-images.githubusercontent.com/7191172/112213126-0e320a00-8c1e-11eb-99c5-b2146e27ae97.png)
I wanted to use build in UI. Can you please advice ?

**Comment by JohnXLivingston** [comment]
Hello,
This is weird. These files should be there. How did you install the plugin? Directly to version 1.0.7, or you updated it from a previous version?

**Comment by JohnXLivingston** [comment]
Can you check your servers logs : https://watch.deranalyst.ch/admin/system/logs, choose «standars logs» in the select.
Then open your browser to https://watch.deranalyst.ch/plugins/livechat/1.0.7/static/conversejs/converse.min.js  and refresh your logs.

When it is working, you should see something like:
``` info[23/03/2021 à 21:37:14] 2a01:: - - [23/Mar/2021:20:37:14 +0000] "GET /plugins/livechat/1.0.7/static/conversejs/converse.min.js HTTP/1.0" 200 1147845 "-" "Firefox" ```

**Comment by Saddamus** [comment]
Installation from UI did not work, so i have installed them over console. 
What I dont understand is that these files do not exist on your git repository, so its not clear for me why should i expect their presence on the server. Should they be created by some scripts during installation or downloaded as dependencies ? They simply are not there on the git by default, this is my question :)

**Comment by JohnXLivingston** [comment]
These files are created when compiling the plugin. If you downloaded the git repo content directly into your peertube directory, you can try to run «npm run build». But this is not the recommended way to install the plugin. I don't know if it will work.

**Comment by Saddamus** [comment]
Thanx a lot, this answers my question. I have managed to install it properly :)
