### ISSUE TITLE
Add a way to shout out to friendly links

### ISSUE THREAD

**Issue by mose** [JohnXLivingston/peertube-plugin-livechat#244]
On twitch, occasionally, people in chat can `shoutout` for other channels, either because they got raided, or the streamer of that other channel interacts in the chat and the streamer wants to promote their friends.

It may involve that streamer has a way to easily keep a record of preferred url, with short names that could be easily used in chat using `!so joe` for example, and the chat bot would reply with `Hey check out the work of joe on https://another.tube/joe`

Ideally it would be good if streamer can custom his default shoutout message, and maybe have a possible shoutout sentence for each preferred link.

Actually links could be of any nature. For example `!so framasoft` could make the chat bot give a relevant block of text with the url to reach framasoft website and bragging about how cool that organisation is.

**Comment by JohnXLivingston** [comment]
If i understand the requested features, it can now be achieved using the bot commands:
https://livingston.frama.io/peertube-plugin-livechat/documentation/user/streamers/bot/commands/index.html

So i close the issue. Feel free to re-open if i missed something.
