### ISSUE TITLE
[Request] Add mod_muc_ban_ip to global modules

### ISSUE THREAD

**Issue by dannekrose** [JohnXLivingston/peertube-plugin-livechat#248]
**Is your feature request related to a problem? Please describe.**
When banning users who don't have XMPP accounts or PeerTube accounts, the ban is only for the JID, not for the IP Address.  A user can just refresh their browser after being banned to be able to rejoin the group chat.

**Describe the solution you'd like**
Add mod_muc_ban_ip (https://modules.prosody.im/mod_muc_ban_ip.html) and allow it to be enabled via a checkbox globally.  I tested it out manually by hacking the prosody.cfg.lua file and adding the module to the livechat prosody-modules directory and it works as expected.

**Describe alternatives you've considered**
The alternative right now is to ban IP addresses via Nginx (or other reverse proxy) which works, but it requires access to the logs to be able to correlate IP addresses and is a lot more effort.

**Additional context**
I know that muc_ban_ip doesn't persist between restarts, but it is a start.  Also, being able to log the banned IPs to the log will help with this (optionally via https://modules.prosody.im/mod_log_auth and using log_auth_ips = "all" 

This is a very sorely needed feature especially as people try to migrate off Twitch or other large streaming services and their followers do not have PeerTube accounts (or even Fediverse Accounts).  Being able to at least provide some level of protection is vital and adding muc_ban_ip will help tremendously towards stopping harassment.

**Comment by JohnXLivingston** [comment]
Hello,

Thanks for pointing out this module, i didn't know it.
If i understand well, mod_muc_ban_ip automatically bans IP when you ban an anonymous user?? This is exactly what i was looking for!

I'm currently working on the first beta for the "moderation bot" (https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/116). I was searching a simple way to ban IPs, without complicated user interface. If i just have to enable this module, it will be really easy!

In the meantime, you can disable access for anonymous users in the plugin settings.
In a near future, each streamer will be able to enable/disable this, per channel.

**Comment by dannekrose** [comment]
> Hello,
> 
> Thanks for pointing out this module, i didn't know it. If i understand well, mod_muc_ban_ip automatically bans IP when you ban an anonymous user?? This is exactly what i was looking for!

This does *exactly* that.  I have set up a small bash script to "manually" install this and restart the prosody appimage with this enabled that I can quickly re-enable every time peertube restarts.

> 
> I'm currently working on the first beta for the "moderation bot" (#116). I was searching a simple way to ban IPs, without complicated user interface. If i just have to enable this module, it will be really easy!
> 

One slight suggestion:
In the mod, there is a line that I suggest you change to "info" level instead of "debug" or at least have as an option to expose the information about which IP was banned so that admins could use that to feed into other tools (such as fail2ban or other tools to ban the IP elsewhere like at Nginx globally, etc)

https://hg.prosody.im/prosody-modules/file/47d9f704d14b/mod_muc_ban_ip/mod_muc_ban_ip.lua

My suggestion is to change this line:
Line 37
	module:log("debug", "Added ban for IP address %s from %s", ip, from);

to this:
	module:log("info", "Added ban for IP address %s from %s", ip, from);

as an option so that it is logged to the prosody.log file for consumption elsewhere as needed.

> In the meantime, you can disable access for anonymous users in the plugin settings. In a near future, each streamer will be able to enable/disable this, per channel.

Of course.  In this case, however, none of the viewers and chatters will have PeerTube or XMPP accounts. The streamers are going to be testing out Live Streaming on PeerTube, but currently are using Twitch.  When they go Live on PeerTube, none of their existing viewers coming to watch will have "accounts" and will all be using the "anonymous" logins and creating nicknames to participate in chat.



As a side note, just enabling this mod should be very very very simple to add to livechat's prosody-modules.  The only things that might make it a little more work are the following:

1. If you want to allow it to be "toggleable" for the entire server/instance, or just for certain channels/rooms.
2. If you want to expose the IP address by making the change above to allow for consuming into some other blocking tools like fail2ban or manually adding to deny lists in Nginx (for example)


Lastly: I *really really* think this should be added quickly even without bot support since, I'll be honest, without it, moderating livechat when the majority of viewers are Anonymous is almost meaningless.

**Comment by JohnXLivingston** [comment]
> > I'm currently working on the first beta for the "moderation bot" (#116). I was searching a simple way to ban IPs, without complicated user interface. If i just have to enable this module, it will be really easy!
> 
> One slight suggestion: In the mod, there is a line that I suggest you change to "info" level instead of "debug" or at least have as an option to expose the information about which IP was banned so that admins could use that to feed into other tools (such as fail2ban or other tools to ban the IP elsewhere like at Nginx globally, etc)
> 
> https://hg.prosody.im/prosody-modules/file/47d9f704d14b/mod_muc_ban_ip/mod_muc_ban_ip.lua
> 
> My suggestion is to change this line: Line 37 module:log("debug", "Added ban for IP address %s from %s", ip, from);
> 
> to this: module:log("info", "Added ban for IP address %s from %s", ip, from);
> 
> as an option so that it is logged to the prosody.log file for consumption elsewhere as needed.

I agree.


> 
> > In the meantime, you can disable access for anonymous users in the plugin settings. In a near future, each streamer will be able to enable/disable this, per channel.
> 
> Of course. In this case, however, none of the viewers and chatters will have PeerTube or XMPP accounts. The streamers are going to be testing out Live Streaming on PeerTube, but currently are using Twitch. When they go Live on PeerTube, none of their existing viewers coming to watch will have "accounts" and will all be using the "anonymous" logins and creating nicknames to participate in chat.

I was just suggesting this if you have some trouble because of bad actors.

> As a side note, just enabling this mod should be very very very simple to add to livechat's prosody-modules. The only things that might make it a little more work are the following:
> 
>     1. If you want to allow it to be "toggleable" for the entire server/instance, or just for certain channels/rooms.

I checked how the module work. No reason to make it toggleable.

>     2. If you want to expose the IP address by making the change above to allow for consuming into some other blocking tools like fail2ban or manually adding to deny lists in Nginx (for example)

I agree.

> Lastly: I _really really_ think this should be added quickly even without bot support since, I'll be honest, without it, moderating livechat when the majority of viewers are Anonymous is almost meaningless.

Will be done this week.

Thanks.

**Comment by JohnXLivingston** [comment]
> Will be done this week.

Will be released monday. I don't want to release it just before the week-end, in case there are some issues to fix.

**Comment by JohnXLivingston** [comment]
Done!
https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/252

After thinking about this feature, I made a settings to enable it.
It is disabled by default.

Indeed, I think there is a security risk on public instances: a bad actor could create an account, create a room, invite some users and ban them. They would be banned for all the server's chatrooms.

Maybe one day i will change my mind, but for now: disabled by default.

**Comment by JohnXLivingston** [comment]
Work like a charm by the way!
Thanks a lot for your issue.

PS: i changed the mod_muc_ban_ip module, so that the log level is "info",  as you requested.

**Comment by dannekrose** [comment]
> Work like a charm by the way! Thanks a lot for your issue.
> 
> PS: i changed the mod_muc_ban_ip module, so that the log level is "info", as you requested.

That's great to hear and I look forward to using the updated version instead of relying on my script!  

I can understand the risk for someone weaponizing it on a public server and understand why you would have it disabled by default.  I think with the logging being able to be fed into something like fail2ban or others, admins will want to evaluate how automated they wish to make it, but the benefits far outweigh potential risks, especially for smaller, trusted servers and thank you for adding this.

**Comment by JohnXLivingston** [comment]
> I can understand the risk for someone weaponizing it on a public server and understand why you would have it disabled by default. I think with the logging being able to be fed into something like fail2ban or others, admins will want to evaluate how automated they wish to make it, but the benefits far outweigh potential risks, especially for smaller, trusted servers and thank you for adding this.

By the way, if you want to write some documentation about how admins could use fail2ban with this feature, feel free to do it!

This could be added in this documentation section:
https://johnxlivingston.github.io/peertube-plugin-livechat/documentation/admin/advanced/

This would be done by adding a markdown file here:
https://github.com/JohnXLivingston/peertube-plugin-livechat/tree/main/support/documentation/content/en/documentation/admin/advanced

**Comment by JohnXLivingston** [comment]
Hi @dannekrose. Plugin was released yesterday.

**Comment by dannekrose** [comment]
Thank you so much!  I don't know how I missed these notifications.  I will take a look and see if I can add some documentation for the fail2ban!
