### ISSUE TITLE
No default language FR applied 

### ISSUE THREAD

**Issue by papaeng** [JohnXLivingston/peertube-plugin-livechat#26]
Hi,
I apply configuration but default language not apply ( fr )

Thanks

**Comment by JohnXLivingston** [comment]
Hello,
Are you talking about the parameter `muc_room_default_language` in the example Prosody configuration? This is only a recommended language for the XMPP room. It has no effect for the webchat. 

For now, i did not handle localization. The built-in webchat is always in english. It is on my roadmap: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/10
I hope have time to fix this next month (april).
I'm closing this issue.
Thanks for your interest in this plugin.
