### ISSUE TITLE
Chat not auto refreshing on V6 - Have to reload page

### ISSUE THREAD

**Issue by MrRoyce** [JohnXLivingston/peertube-plugin-livechat#277]
I just installed a new instance of PeerTube and livechat.  The chat messages are not refreshed unless I reload the page.

**To Reproduce**
View livestream in multiple clients 
Enter message in chat window for a client

**Expected behavior**
The messages are refreshed for all client

**Screenshots**
N/A

**Server (please complete the following information):**
 - OS version Ubuntu 2204
 - Peertube version:  6
 - Peertube installation type [e.g. standard, docker, ...]: Standard
 - peertube-plugin-livechat version: Latest
 - Chat mode if relevant [disabled, Prosody, external XMPP, external]: Not sure

**Plugin diagnostic:**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS, iOS
 - Browser Chrome, Brave

**Additional context**
Not sure what else is needed to diagnose this

**Comment by JohnXLivingston** [comment]
Hello,
I'm closing this issue as there were no response to my precedent comment. I have not enough information to debug.
If you still have the issue, feel free to re-open. And give me a link to an active chat on your instance, so  i can check.
