### ISSUE TITLE
Duplicate on the diagnostic page on two lines. (Everything seems fine: OK)

### ISSUE THREAD

**Issue by rnek0** [JohnXLivingston/peertube-plugin-livechat#293]
Is it the same test, or two different tests but with the same message? 

![diagnostique](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/52655832/33af7696-6b24-4781-a794-91ed9c3d9c24)

**Comment by JohnXLivingston** [comment]
This is a similar test, in two different functions.
The tests are divided in multiple batches. Here, we have 2 functionalities that are testing that the configuration file exists, and is readable: one that checks if we can control prosody, and one that checks if prosody is running.

So: yes it is duplicate code (exact same test at 2 different spots), but this is not an issue. Perhaps i should add a line at the beggining of each batch, so we can better understand.
