### ISSUE TITLE
UI: add a separator above message field

### ISSUE THREAD

**Issue by JohnXLivingston** [JohnXLivingston/peertube-plugin-livechat#311]
**Describe the bug**

When message field has not the focus, there is a missing border:

![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/c98b5a1c-581b-4323-88e1-a7c9809e4f10)

![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/169bcc0e-7781-4511-a067-9a74124e2631)

Edit by John:
Other thinks to fix:
* [x] the blue color when the textarea has the focus is not the correct one
* [ ] blue outlines on input fields should not be blue
* [x] have consistent outline behaviour between browsers

**Comment by jeey** [comment]
in addition, the background color between a field and a non-clickable zone is the same, which is a little confusing (for me) on where I can click to write my message.

**Comment by JohnXLivingston** [comment]
And for the record, part of the issue was some inconsistency between firefox and chrome:
https://github.com/conversejs/converse.js/issues/3307

**Comment by JohnXLivingston** [comment]
For the border issue:

Without focus
![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/168e3c57-1e42-4d5c-9896-e9c6ddc3c391)
With focus
![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/f419a9a8-198f-4ae6-a719-d80cea267ea0)


Same for dark mode:
![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/e61247b7-3bc2-4ace-8ec4-a36ec1fd5f28)
![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/38844060/39852ee1-f595-4735-ba1f-cc84e4a01744)


Concerning the background-color, i'm not changing it for now. I don't have enough colors (i must stick with Peertube colors, that has less colors than ConverseJS ; otherwise it will not work for every custom Peertube themes).

**Comment by JohnXLivingston** [comment]
Fixed by https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/312

**Comment by JohnXLivingston** [comment]
Can be tested here: https://videos.john-livingston.fr/w/qqNQwFDerUB1KnFA6N6Jbi (must clear the browser cache)

**Comment by jeey** [comment]
Seems nice here 
![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/10157300/8628b9fe-cf04-4221-8573-ea88e5dbb928)
