### ISSUE TITLE
poor contrast in Dark mode for the nickname text field

### ISSUE THREAD

**Issue by jeey** [JohnXLivingston/peertube-plugin-livechat#314]
The text entered in the "Nickname" field is not contrasted enough to make it easy to read

![image](https://github.com/JohnXLivingston/peertube-plugin-livechat/assets/10157300/a3cd301c-b9c4-485c-b8b6-0fd3cccedff3)

Firefox Nightly 124 - Linux Mint 21

**Comment by JohnXLivingston** [comment]
Fixed by https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/319
Screenshots in the PR.
