### ISSUE TITLE
Allow non-localhost C2S connections for Matterbridge 

### ISSUE THREAD

**Issue by poVoq** [JohnXLivingston/peertube-plugin-livechat#377]
Given that configuring a Matterbridge can not be easily automated, it is usually left to the streamers themselves to set up bridging, however many Peertube admins are not so XMPP affine and thus do not set up full S2S federation as outlined [here](https://livingston.frama.io/peertube-plugin-livechat/documentation/admin/advanced/xmpp_clients/).

There is an easier way to connect directly via C2S and SASL anonymous as explained in [this tutorial](https://gitlab.com/refrac/obs-matterbridge-overlay/-/blob/master/documentation/peertube.md), but it requires direct access to the server that Peertube runs on as currently the built in Prosody server is limited to localhost C2S connections.

It would probably be good to allow non-localhost C2S connections, as this would significantly simplify bridging via Matterbridge and allow streamers themselves to quickly setup a bridge during their streams with no direct involvement of the main Peertube admin, nor the need of involving an external XMPP server as in the case of a full S2S connection.

Furthermore it would be significantly simpler to set up for non xmpp affine Peertube admins as it should be as simple as opening port 5222 with no strict need to have proper SSL certificates (which most XMPP server require for S2S these days) and probably also no XMPP DNS entries.

Caveats would be that this would expose the internal Prosody to bruteforce auth attempts on the C2S interface though, which might require some additional precautions.

Ideally this option should be documented [here](https://livingston.frama.io/peertube-plugin-livechat/documentation/admin/advanced/matterbridge/) to make it easy to explain to non xmpp affine Peertube admins.

Thanks a lot!

**Comment by JohnXLivingston** [comment]
Done in https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/393

If you want to add some documentation, be my guest :)

**Comment by JohnXLivingston** [comment]
PS: i don't know when the next plugin version will be released. We have some refactoring to finish before.
