### ISSUE TITLE
Very noisy error logging

### ISSUE THREAD

**Issue by polykit** [JohnXLivingston/peertube-plugin-livechat#441]
**Describe the bug**
Since a few versions the following error message is constantly logged:

```
error[6/20/2024, 4:41:55 PM] internal
{
  "result": {
    "chat-per-live-video": true,
    "chat-all-lives": false,
    "chat-all-non-lives": false,
    "chat-videos-list": "",
    "disable-websocket": true,
    "prosody-room-type": "video",
    "federation-dont-publish-remotely": true,
    "chat-no-anonymous": false,
    "prosody-room-allow-s2s": false,
    "prosody-s2s-port": "5269"
  }
}
```

It looks like it's happening with every site access.

**Expected behavior**
Error logging is not that noisy or can be turned off.

**Server (please complete the following information):**
 - OS version [e.g. Debian 10, ...]: Ubuntu 22.04 LTS
 - Peertube version: 6.1.0
 - Peertube installation type [e.g. standard, docker, ...]: docker
 - peertube-plugin-livechat version: 10.1.0
[livechat-diag.txt](https://github.com/user-attachments/files/15917047/livechat-diag.txt)

**Plugin diagnostic:**
See attachment

**Comment by JohnXLivingston** [comment]
This is a Peertube but that will be fixed in next release: https://github.com/Chocobozzz/PeerTube/issues/6374

It happens everytime a plugin (not only livechat) reads its settings.
