### ISSUE TITLE
Allow option to have custom emoji shortnames not use the colon before and after.

### ISSUE THREAD

**Issue by dannekrose** [JohnXLivingston/peertube-plugin-livechat#449]
**Is your feature request related to a problem? Please describe.**
This is not a problem.  This is a feature request to allow shortnames for custom emoji to not require a colon at the beginning and end of the shortname.

**Describe the solution you'd like**

Currently, when creating or importing a custom emoji, the shortname requires a colon ( : ) before and after the shortname:
example:
:myCustomEmoji: 

This solution would allow for shortnames that don't require the colons.
Example:
myCustomEmoji
 
In the JSON, it would look like this (after adding this feature):

[{"sn":"myCustomEmoji","url":"data:image...." ...

**Describe alternatives you've considered**

This doesn't have an easy workaround.  I haven't modified the underlying javascript code to remove the colons, but I suspect this is possible but requires CLI access and knowledge of the plugin's code structure.

**Additional context**
When linking peertube live chat with Twitch, custom emoji on twitch often do not have the colons in the emoji shortname.  This means that even with the same name for a custom emoji on Twitch and PeerTube Live Chat, they won't show up in the other service's chat as rendered due to the emoji shortnames being different.

**Comment by JohnXLivingston** [comment]
Fixed.
