### ISSUE TITLE
ConverseJS fullscreen: wrong window title

### ISSUE THREAD

**Issue by JohnXLivingston** [JohnXLivingston/peertube-plugin-livechat#46]
**Describe the bug**

The title of the page is «Converse». Should not.

**Comment by germanfung** [comment]
Hi, are you referring to this error? I got the 404 in the diagnostic.

I am running freebsd, prosody-0.11.9 and prosody-modules-20200302
     
Builtin Prosody and ConverseJS: KO
The working dir is: /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
Prosody will run on port '52800'
Prosody will use https://video.in.lchs.network/plugins/livechat/3.1.0/router/api/ as base uri from api calls
Prosody modules path will be '/var/www/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
Prosody configuration file content is correct.
Pid file /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
Prosodyctl status: Prosody is running with PID 1298
The prosody configuration file (/var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
Prosody configuration file content is correct.
Prosody version is 0.11.9
Error when calling Prosody test api (test-peertube-prosody): HTTPError: Response code 404 (Not Found)

![image](https://user-images.githubusercontent.com/46979868/124528490-9d6cd180-de4b-11eb-9b3b-61ff462976af.png)

**Comment by JohnXLivingston** [comment]
No, your issue @germanfung seems to be the same as https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/56 .
Please try to add http://localhost:9000 in the setting «Peertube url for API calls» (supposing your Peertube is listening on port 9000). Then try the webchat (the diagnostic tool will remain broken for now).

**Comment by germanfung** [comment]
yup, fixed by http://localhost:9000, thx
