### ISSUE TITLE
Avatars Do Not Display on Latest Commit

### ISSUE THREAD

**Issue by MattyBoombalatty** [JohnXLivingston/peertube-plugin-livechat#476]
Self explanatory. Avatars do not load. Perhaps a Converse bug?

![image](https://github.com/user-attachments/assets/a38ff00c-c8d6-4ba7-b8c6-cb2fc35d2b82)

**Comment by JohnXLivingston** [comment]
What version are you using? This screenshot use a feature that is not released yet. The current main branch is a long term WIP. This bug, if it is the bug i assume, was fixed yesterday.

Please fill the bug report template when you open an issue. To save me time.

**Comment by MattyBoombalatty** [comment]
Sorry about that, I keep up with the main branch just like I do on every other project so that I can help test. In the future I'll fill out the template. Thank you.

**Comment by JohnXLivingston** [comment]
> Sorry about that, I keep up with the main branch just like I do on every other project so that I can help test. 

Ok, that's fine. Thanks.

**Comment by JohnXLivingston** [comment]
Have you tried a new version since the other day. Can you confirm it is okay now?
