### ISSUE TITLE
Add Ability To Modify Username Color 

### ISSUE THREAD

**Issue by MattyBoombalatty** [JohnXLivingston/peertube-plugin-livechat#524]
**Is your feature request related to a problem? Please describe.**

It's not necessarily an issue, but it appears that most user names, both registered and anonymous are an ugly brown color rather than a mixture of other lighter and darker colors. This wasn't an issue on 10.3.3 but since updating to 11.0.1, it seems admin/moderator names are the only ones that are different. How is this calculated? I can just maintain my own fork but I am unable to find the CSS selectors for the colors.

**Comment by JohnXLivingston** [comment]
Colors are generated accordingly with https://xmpp.org/extensions/xep-0392.html
The code is in ConverseJS, not in the plugin.
You can use the ConverseJs `colorize_username` option to disable this.
https://github.com/conversejs/converse.js/blob/a9e3b237b24388d3eac4de6bd34bb85a30a99764/docs/source/configuration.rst#L2196

**Comment by JohnXLivingston** [comment]
If you want to submit a PR with a new option to disable user colors, feel free.
