### ISSUE TITLE
Possibility to make chat only for registered users

### ISSUE THREAD

**Issue by Roki100** [JohnXLivingston/peertube-plugin-livechat#54]
**Is your feature request related to a problem? Please describe.**
The problem could show up while there are more chat users, when the chat does not require an account it could potentially cause a mess and spam

**Describe the solution you'd like**
Some message telling the user to log in/register in order to chat in the livechat, the great example of such solution would be twitch/youtube

**Describe alternatives you've considered**
I didnt consider any alternatives yet

**Additional context**
This would be useful for bigger instances aswell as making it easier to moderate the chat

**Comment by Mundo-Desconocido** [comment]
It would be great if this possibility could be implemented.
Thank you

**Comment by JohnXLivingston** [comment]
Feature added in commit https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/01a052d3806e5a6c405459d4027701e856a9842d

This is a first version. Will be enhanced later on (so I'm keeping this issue open).

**Comment by JohnXLivingston** [comment]
@Roki100 , for this feature, what did you have in mind for unregistered users:

* they can only read the chat ?
* they can't even read the chat

And what about users registered on remote Peertube instances?
