### ISSUE TITLE
Livechat won't load on NixOS

### ISSUE THREAD

**Issue by BRBWaffles** [JohnXLivingston/peertube-plugin-livechat#540]
**Describe the bug**
I'm running PeerTube on my NixOS server. I logged in, downloaded the plugin, and used every combination of settings and was never able to get the livechat plugin to work. It just shows a loading pinwheel, or tells me the chat doesn't exist with certain settings.

**To Reproduce**
1. Declare the PeerTube NixOS service module.
2. Log in.
3. Navigate to the plugin tab in the Administration settings.
4. Download the plugin.
5. Try different recommended settings.
6. Launch livestream.
7. See nothing.
8. Repeat.

**Expected behavior**
I expected to see a chat box that I, and viewers, could interact with.

**Server (please complete the following information):**
 - OS version: NixOS unstable 24.11.20240911.4f807e8
 - Peertube version: 6.0.4
 - Peertube installation type: NixOS service module.
 - peertube-plugin-livechat version: 11.0.1

**Plugin diagnostic:**
```
    Starting tests: OK
    Browser: OK
    Backend connection: OK
    Test debug mode: OK
        Debug mode is OFF
    Webchat activated on videos: OK
        Chat will open automatically
        Displaying «open in new window» button
        Chat can be enabled on live videos.
        Chat is enabled for all lives.
    Builtin Prosody and ConverseJS: KO
        The working dir is: /var/lib/peertube/storage/plugins/data/peertube-plugin-livechat/prosody
        Prosody will run on port '52800'
        Prosody will use http://127.0.0.1:9000/plugins/livechat/11.0.1/router/api/ as base uri from api calls
        Prosody path will be '/var/lib/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage/squashfs-root/AppRun'
        Prosody will be using the '/var/lib/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody/livechat-prosody-x86_64.AppImage' AppImage
        Prosody AppImage extract path will be '/var/lib/peertube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage'
        Prosody modules path will be '/var/lib/peertube/storage/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
        Prosody rooms will be grouped by 'video'.
        By default, room content will be archived.
        Room content will be saved for '1w'
        Error when requiring the prosody config file: Error: ENOENT: no such file or directory, access '/var/lib/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua'
```
Also, no AppImage is installed in the /PeerTube/storage/plugins/data/peertube-plugin-livechat/prosodyAppImage directory, nor is a config file provided.

**Desktop (please complete the following information):**
 - OS: NixOS
 - Browser: Firefox
 - Version: 130.0

**Comment by JohnXLivingston** [comment]
Hello,

Is the  `/var/lib/peertube/storage/plugins/data/peertube-plugin-livechat/` directory writable for the `peertube` user?

Did you see that the livechat plugin is packaged for Nix? Have you tried this package?
https://github.com/ngi-nix/ngipkgs/tree/init/peertube-plugins/livechat/pkgs/by-name/peertube-plugin-livechat

I'm not familiar with NixOS (I only heard about it), so i don't know if there are some restrictions to overcome.

**Comment by BRBWaffles** [comment]
Thanks for the quick reply.

Yes, the `peertube` user has read/write permissions to `/var/lib/peertube/storage/plugins/data/peertube-plugin-livechat/`. The directory populates with `/bot`, `/prosody`, and `prosodyAppImage` upon the installation of the `livechat` plugin. However, the `/prosodyAppImage` directory is empty. The permissions to the directory are currently `750`, but I've also tried `770` and `700`. I also tried installing the package via to `ngipkgs` option you provided, but I'm also running into permission issues there as well. The entire `/var/lib/peertube` directory has recursive `750` permissions and should be completely readable and writable by the `peertube` user. It's not clear at all to me what is wrong with my configuration.

**Comment by JohnXLivingston** [comment]
So, could we consider this issue as closed? (for now...)

If you have troubles again, maybe try to ask the maintainer of the peertube nix package. There might be some specifics with NixOS that i'm not aware of.
And if you have some solution, feel free to share (here, or even by making a pull request on the documentation: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/support/documentation/content/en/documentation/installation/troubleshooting.md )

**Comment by BRBWaffles** [comment]
Yeah, it's fair to call it closed. I dunno what was up. Probably just some stateful stuff that disappeared when I was messing around with something. Not clear what, but it's working now. No clear solution, despite it working, unfortunately.
