### ISSUE TITLE
Chat problem

### ISSUE THREAD

**Issue by Alterak** [JohnXLivingston/peertube-plugin-livechat#55]
Hello. I saw an update for your plugin and decided to try to install it, but after installation (as written in the instructions), the chat did not work for me.
I am using an external chat server that is powered by Rocket Chat. It is of course very convenient, but I lack the knowledge to fully integrate it with video IDs and Peertube accounts.

I videotaped the entire plugin installation process. Tell me what I did wrong?

https://peervideo.ru/videos/watch/6d7ff5e5-f9f7-49b4-8633-255edd90bb6b

**Comment by JohnXLivingston** [comment]
Hello,

Have you a very restrictive firewall on your server? Is the port 52800 open for listening on localhost?
You can try this (on your server):
```
curl http://127.0.0.1:52800/http-bind
```
It should display something like:
```
<html><body>
<p>It works! Now point your BOSH client to this URL to connect to Prosody.</p>
<p>For more information see <a href="https://prosody.im/doc/setting_up_bosh">Prosody: Setting up BOSH</a>.</p>
</body></html>
```

If it is not working, try to check your firewall to allow port 52800 on localhost.

If it is working, try to add this value in the setting «Peertube url for API calls» : `http://127.0.0.1:9000` (if Peertube is running on port 9000). 
Then, go to a video with webchat enabled to check if it is working.
There might be a bug on the diagnostic tool on some servers, where `localhost` is not correctly resolved. I don't know why this happens.



You can also try to set your peertube server log level to «debug» (in Peertube's config file), and restart your server. Then, you should have more logs in prosody.log and prosody.err.

**Comment by Alterak** [comment]
> Have you a very restrictive firewall on your server? Is the port 52800 open for listening on localhost?

But after all, on debian all ports are open by default-)
Here is a check ... as you can see port 52800 is open for listening

peertube@peervideo:~$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      591/postgres
tcp        0      0 127.0.0.1:61209         0.0.0.0:*               LISTEN      540/python3
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      670/nginx: master p
tcp        0      0 127.0.0.1:52800         0.0.0.0:*               LISTEN      8957/lua5.2
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      30306/peertube
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      630/redis-server 12
tcp        0      0 0.0.0.0:38125           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:41293           0.0.0.0:*               LISTEN      517/rpc.mountd
tcp        0      0 0.0.0.0:58799           0.0.0.0:*               LISTEN      517/rpc.mountd
tcp        0      0 0.0.0.0:53391           0.0.0.0:*               LISTEN      517/rpc.mountd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      670/nginx: master p
tcp        0      0 0.0.0.0:2227            0.0.0.0:*               LISTEN      668/sshd
tcp6       0      0 :::38455                :::*                    LISTEN      517/rpc.mountd
tcp6       0      0 :::5432                 :::*                    LISTEN      591/postgres
tcp6       0      0 :::443                  :::*                    LISTEN      670/nginx: master p
tcp6       0      0 ::1:52800               :::*                    LISTEN      8957/lua5.2
tcp6       0      0 :::2049                 :::*                    LISTEN      -
tcp6       0      0 :::59077                :::*                    LISTEN      517/rpc.mountd
tcp6       0      0 :::36327                :::*                    LISTEN      -
tcp6       0      0 ::1:6379                :::*                    LISTEN      630/redis-server 12
tcp6       0      0 :::1935                 :::*                    LISTEN      30306/peertube
tcp6       0      0 :::111                  :::*                    LISTEN      1/init
tcp6       0      0 :::80                   :::*                    LISTEN      670/nginx: master p
tcp6       0      0 :::53297                :::*                    LISTEN      517/rpc.mountd
tcp6       0      0 :::2227                 :::*                    LISTEN      668/sshd
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/init
udp        0      0 0.0.0.0:45204           0.0.0.0:*                           517/rpc.mountd
udp        0      0 0.0.0.0:49395           0.0.0.0:*                           517/rpc.mountd
udp        0      0 0.0.0.0:2049            0.0.0.0:*                           -
udp        0      0 0.0.0.0:35720           0.0.0.0:*                           517/rpc.mountd
udp        0      0 0.0.0.0:48261           0.0.0.0:*                           -
udp6       0      0 :::45070                :::*                                -
udp6       0      0 :::111                  :::*                                1/init
udp6       0      0 :::2049                 :::*                                -
udp6       0      0 :::44043                :::*                                517/rpc.mountd
udp6       0      0 :::53013                :::*                                517/rpc.mountd
udp6       0      0 :::49005                :::*                                517/rpc.mountd
peertube@peervideo:~$

**Comment by Alterak** [comment]
I have enabled debug mode in the peertube config file, now I see such a log for prosody
```
Jun 27 20:57:31 http.server     debug   Firing event: POST /http-bind
Jun 27 20:57:31 mod_bosh        debug   Handling new request table: 0x557faafead90: <body content="text/xml; charset=utf-8" hold="1" rid="3435439233" to="peervideo.ru" ver="1.6" wait="59" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0"/>
----------
Jun 27 20:57:31 mod_bosh        debug   BOSH body open (sid: <none>)
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   BOSH session created for request from 192.168.1.10
Jun 27 20:57:31 mod_bosh        info    New BOSH session, assigned it sid 'ce58dc11-9ac5-486c-9fdf-6ea6aa31870d'
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   rid: 3435439233, sess: 3435439232, diff: 1
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   Offering mechanism PLAIN
Jun 27 20:57:31 mod_bosh        debug   We have an open request, so sending on that
Jun 27 20:57:31 mod_bosh        debug   Request destroyed: table: 0x557faaff66b0
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   BOSH session marked as inactive (for 60s)
Jun 27 20:57:31 socket  debug   server.lua: closed client handler and removed socket from list
Jun 27 20:57:31 mod_bosh        debug   Session ce58dc11-9ac5-486c-9fdf-6ea6aa31870d has 0 out of 1 requests open
Jun 27 20:57:31 mod_bosh        debug   and there are 0 things in the send_buffer:
Jun 27 20:57:31 socket  debug   server.lua: accepted new client connection from 127.0.0.1:44192 to 52800
Jun 27 20:57:31 http.server     debug   Firing event: POST /http-bind
Jun 27 20:57:31 mod_bosh        debug   Handling new request table: 0x557fab05d720: <body rid="3435439234" sid="ce58dc11-9ac5-486c-9fdf-6ea6aa31870d" xmlns="http://jabber.org/protocol/httpbind"><auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">AG9uaXgAc3g5YWxlYWNnYTE4Nm92ZWM3YXA=</auth></body>
----------
Jun 27 20:57:31 mod_bosh        debug   BOSH body open (sid: ce58dc11-9ac5-486c-9fdf-6ea6aa31870d)
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   rid: 3435439234, sess: 3435439233, diff: 1
Jun 27 20:57:31 mod_bosh        debug   BOSH stanza received: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>

Jun 27 20:57:31 runner29L4OKxv  debug   creating new coroutine
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   Received[c2s_unauthed]: <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Jun 27 20:57:31 http    debug   Making HTTPS GET request '557faafb9a90' to https://peervideo.ru/plugins/livechat/3.1.0/router/api/user/check_password?user=onix&server=peervideo%2eru&pass=sx9aleacga186ovec7ap
Jun 27 20:57:31 net.connect     debug   [pending connection qrZYIi7N] Starting connection process
Jun 27 20:57:31 net.connect     debug   [pending connection qrZYIi7N] Checking for targets...
Jun 27 20:57:31 adns    debug   Records for peervideo.ru not in cache, sending query (thread: 0x557fab06aae0)...
Jun 27 20:57:31 adns    debug   Sending DNS query to 192.168.2.11
Jun 27 20:57:31 adns    debug   Records for peervideo.ru not in cache, sending query (thread: 0x557fab0303f0)...
Jun 27 20:57:31 adns    debug   Sending DNS query to 192.168.2.11
Jun 27 20:57:31 runner29L4OKxv  debug   changed state from ready to waiting
Jun 27 20:57:31 mod_bosh        debug   Session ce58dc11-9ac5-486c-9fdf-6ea6aa31870d has 1 out of 1 requests open
Jun 27 20:57:31 mod_bosh        debug   and there are 0 things in the send_buffer:
Jun 27 20:57:31 mod_bosh        debug   Have nothing to say, so leaving request unanswered for now
Jun 27 20:57:31 adns    debug   Reply for peervideo.ru (thread: 0x557fab06aae0)
Jun 27 20:57:31 socket  debug   server.lua: closed client handler and removed socket from list
Jun 27 20:57:31 adns    debug   Reply for peervideo.ru (thread: 0x557fab0303f0)
Jun 27 20:57:31 net.connect     debug   [pending connection qrZYIi7N] Next target to try is 192.168.2.27:443
Jun 27 20:57:31 socket  debug   server.lua: auto-starting ssl negotiation...
Jun 27 20:57:31 socket  debug   server.lua: attempting to start tls on tcp{client}: 0x557fab081618
Jun 27 20:57:31 socket  debug   server.lua: ssl handshake done
Jun 27 20:57:31 net.connect     debug   [pending connection qrZYIi7N] Successfully connected
Jun 27 20:57:31 http    debug   Request '557faafb9a90': Calling callback, status 0
Jun 27 20:57:31 peervideo.ru:saslauth   debug   sasl reply: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/><text>Unable to authorize you with the authentication credentials you&apos;ve sent.</text></failure>
Jun 27 20:57:31 mod_bosh        debug   We have an open request, so sending on that
Jun 27 20:57:31 mod_bosh        debug   Request destroyed: table: 0x557fab05d7a0
Jun 27 20:57:31 boshce58dc11-9ac5-486c-9fdf-6ea6aa31870d        debug   BOSH session marked as inactive (for 60s)
Jun 27 20:57:31 socket  debug   server.lua: closed client handler and removed socket from list
Jun 27 20:57:31 runner29L4OKxv  debug   changed state from waiting to ready
Jun 27 20:57:31 socket  debug   server.lua: closed client handler and removed socket from list
```

**Comment by Alterak** [comment]
Forgive me, it was my mistake- (
I completely forgot about the additional NGINX configuration I was doing for the chat. I disabled it and now everything works correctly.

**Comment by JohnXLivingston** [comment]
That is a great news!

**Comment by JohnXLivingston** [comment]
There were modifications to do on nginx configuration on an old plugin version. Then I manage to use Peertube as reverse proxy :)
