### ISSUE TITLE
Impopssible to join chat

### ISSUE THREAD

**Issue by JamesDAdams** [JohnXLivingston/peertube-plugin-livechat#56]
**Describe the bug**
Impossible to join chat

**To Reproduce**
1. Go to 'a video or live'
2. Click on 'enter groupchat'
4. See error in console browser

**Expected behavior**
have the chat that works

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/20860324/124158813-ac91ff00-da9a-11eb-97a7-c38b8daea321.png)

**Server (please complete the following information):**
 - OS version [e.g. Debian 10, ...]: Unraid
 - Peertube version: 3.2.1
 - Peertube installation type [e.g. standard, docker, ...]: Docker
 - peertube-plugin-livechat version: 3.1.0

**Plugin diagnostic:**
![Sans titre](https://user-images.githubusercontent.com/20860324/124159414-6e490f80-da9b-11eb-9518-3c2b8a6e880b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome & Edge
 - Version [e.g. 22] Chrome: 91.0.4472.124  Edge: 91.0.864.59

**Additional context**

**Comment by JamesDAdams** [comment]
I add http://localhost:9000 in **Peertube url for API calls** and it's work

**Comment by JohnXLivingston** [comment]
Ok. 
It seems that this issue is more frequent than I imagined. Thanks for the feedback.
