### ISSUE TITLE
Option to use room linked to the channel

### ISSUE THREAD

**Issue by tytan652** [JohnXLivingston/peertube-plugin-livechat#58]
**Is your feature request related to a problem? Please describe.**
I'm actually trying to provide a chat overlay for OBS Studio, it actually use Matterbridge API as message provider.
Matterbridge can also unify different chat solution as one for the overlay enabling a nice double-stream chat overlay.
The issue is that only PeerTube require to change the room in the config for each live on the same channel. And restarting Matterbridge if someone else is using the solution is not a good idea.
Using permanent live which unfortunately use live slot even if not streaming, so it's not a solution.

**Describe the solution you'd like**
So I thought, what about creating a room related to the channel and make channel's live able to use it when needed.
It will add an option when creating a video to use a room related to the channel rather than the video.
So any live from the same channel with this option enabled will provide the same room.

It could also enable the possibility to recover the room, if a crash happen on a non-permanent live.
Note: There is no need to keep the room alive all the time.

**Describe alternatives you've considered**
Like I said changing the config manually on the server each time is not convenient and worse if someone is already streaming and using the solution.

**Additional context**
I tried to implement it myself but I'm beginner at JS/TS but I don't think I'd be able to make it.
If you want I can push my draft of the attempt in my repo.

**Comment by JohnXLivingston** [comment]
I understand your need. I think I will add this to my roadmap. But I can't promise you a release date. 
No need to commit your attempt.

**Comment by tytan652** [comment]
The fact that you add it to your roadmap is enough. When I ask a feature, I wait for a yes or a no, not a release date

**Comment by JohnXLivingston** [comment]
This feature is implemented for the «ConverseJS with external XMPP server» mode in this commit: https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/a3579abb8160cfdba192be106e15033bbd826616

You can now use placeholders CHANNEL_ID and CHANNEL_NAME.

More to come in future commits:
- allow placeholders USER_ID and USER_NAME
- do the same for the «external chat tool» mode
- do a similar feature for the «builtin Prosody» mode (I think users will have the choice for each video)

**Comment by JohnXLivingston** [comment]
This feature is available in the v4.0.0, that was just release: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/v4.0.0/CHANGELOG.md
