### ISSUE TITLE
Can I see a demo of how this works?

### ISSUE THREAD

**Issue by vachan-maker** [JohnXLivingston/peertube-plugin-livechat#59]
I  don't really know how to self host.
Can I see a demo?
This is a really cool plugin

**Comment by JohnXLivingston** [comment]
There is a public demo here: https://www.yiny.org/videos/watch/399a8d13-d4cf-4ef2-b843-98530a8ccbae
For the full page view: https://www.yiny.org/plugins/livechat/3.2.0/router/webchat/room/399a8d13-d4cf-4ef2-b843-98530a8ccbae (or by using the button just on top of the webchat besides the video).

Here is a video, in french, were I talked about new features coming with version 3.0.0: https://videos.globenet.org/videos/watch/7e943002-d15c-4422-8d4f-af9098e3e64e
Current version is 3.2.0.

The recommanded (and standalone) installation procedure is documented here: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md

Does this answer your question?
