### ISSUE TITLE
Chat stuck at converse.js splash screen

### ISSUE THREAD

**Issue by Casuallynoted** [JohnXLivingston/peertube-plugin-livechat#63]
Hello,

I'm using the Prosody controlled by PeerTube method, and diagnostics claim that everything is configured correctly. However, the chat just provides a converse.js splash screen.

Link to server/live: https://videos.casually.cat/w/a7fc0325-eb8d-4795-99b5-ce2ed7d6f8b3
![image](https://user-images.githubusercontent.com/6272557/127821510-2413723d-8665-4034-b256-22368c90a039.png)

**Comment by Casuallynoted** [comment]
As an update, this seems to only be affecting me when I'm signed in. If I visit the page anonymously, it prompts me to enter a nickname.

**Comment by Casuallynoted** [comment]
Absolutely, here is that information:

Prosody version: Originally 0.11.4-1, upgraded to 11.9 latest and issue persists

Console information:
pluggable.js:163 Plugin "converse-muc-views" tried to override "ControlBoxView" but it's not found.
throwUndefinedDependencyError @ pluggable.js:163
pluggable.js:163 Plugin "converse-headlines-view" tried to override "ControlBoxView" but it's not found.
throwUndefinedDependencyError @ pluggable.js:163
log.js:66  2021-08-02T14:18:33.838Z WARNING: Could not restore session for jid: casuallynoted@videos.casually.cat/converse.js-90418969 Error message: _restore: no restoreable session. 

No errors or warnings in the standard error logs.

**Comment by JohnXLivingston** [comment]
Hum. Can you create me an account on your instance? With the email testcasually@john-livingston.fr ?

**Comment by Casuallynoted** [comment]
Absolutely! Just created!

**Comment by JohnXLivingston** [comment]
Is your instance correctly configured to send mails? I did not receive any mail for setting my password (even after using the «recover password» feature)

**Comment by JohnXLivingston** [comment]
You can also check for logs in /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.err and /var/www/peertube/storage/plugins/data/peertube-plugin-livechat/prosody/prosody.log.
If there is nothing in this files, you can have more verbose logs by changing the log level in the peertube config file to `debug` and then restart your peertube server.

Was it working with prosody 0.11.4-1? I just realized that I only tested with Prosody 0.11.2 (debian stable).

**Comment by Casuallynoted** [comment]
> Is your instance correctly configured to send mails? I did not receive any mail for setting my password (even after using the «recover password» feature)

Whoops! Fixed this issue, my email server changed configs and forgot to update on Peertube since I haven't had to! 

Nothing in the log files, changing to debug and gonna see if that shows anything.

**Comment by Casuallynoted** [comment]
So with debug turned on, the error file still has nothing but attached is the prosody log:
[prosody.log](https://github.com/JohnXLivingston/peertube-plugin-livechat/files/6918626/prosody.log)

**Comment by JohnXLivingston** [comment]
That is really weird... It is working for me.
Can you try with a private window in your browser?
It may by ConverseJS who is caching bad data in your browser local storage.

**Comment by Casuallynoted** [comment]
> That is really weird... It is working for me.
> Can you try with a private window in your browser?
> It may by ConverseJS who is caching bad data in your browser local storage.

Weirdly enough, it still doesn't work when using via private mode, in another browser, or even on another device :O

**Comment by JohnXLivingston** [comment]
What is your browser?
Is it working if you connect to your instance with another user?

If you open the chat in a full window, then if you open your browser console on the network tab and refresh the page, there should be a request on https://videos.casually.cat/plugins/livechat/3.2.0/router/api/auth . What is the http return code of this request? The response should be a JSON object that contains a jid, a nickname and a password. Is this correct?

**Comment by Casuallynoted** [comment]
I've been testing using Chrome, Safari, and Firefox so far on different machines. Interestingly enough, the request does come out properly with a kid, nickname, and password but still no dice when logged into my account. However! When I make a new account and log into that, the chat works and loads properly. So it has to be something to do with my account, but I have no clue what that would be ^^;

**Comment by JohnXLivingston** [comment]
What are your username and nickname? Is there any special chars?

**Comment by Casuallynoted** [comment]
My username and nickname are "Casuallynoted", with a capital c. No special characters.

**Comment by JohnXLivingston** [comment]
The peertube interface don't let you use capital letters for the username. How have you created this user?

**Comment by Casuallynoted** [comment]
I created it via peertube, but it was on an older version. Maybe it used to allow it?

**Comment by JohnXLivingston** [comment]
> I created it via peertube, but it was on an older version. Maybe it used to allow it?

Maybe.
If you do this request on your database:
```posgres
select "username" from "user";
```

Is there a capital letter?

**Comment by JohnXLivingston** [comment]
I can confirm that it is related to this uppercase letter.
Request on `https://videos.casually.cat/plugins/livechat/3.2.0/router/api/user/user_exists?user=Casuallynoted&server=videos.casually.cat` gives true, and on `https://videos.casually.cat/plugins/livechat/3.2.0/router/api/user/user_exists?user=casuallynoted&server=videos.casually.cat` gives false.

If I check Peertube's code, capital letter should not be allowed in nicknames: 
https://github.com/Chocobozzz/PeerTube/blob/ff4de38385049bf8f6e1d76d8511854fcfabc71c/server/helpers/custom-validators/users.ts#L29-L33

So I don't want to fix this by making the username lowercase...
Sorry, but I don't know how to fix this properly.

**Comment by JohnXLivingston** [comment]
After a night of thinking, i will finally fix this. I found code in Peertube that lowercase the username to check unicity. So I can assume there will never be two users with nicknames like «casuallynoted» and «Casuallynoted» (the risk would have been that a user can impersonate a person by taking the same nickname with a capital letter).

**Comment by JohnXLivingston** [comment]
Fixed in https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/3ca97fcf0eb74a6440dbbccdd4b62a2fdf210fc6
Will be released soon (probably today).

**Comment by JohnXLivingston** [comment]
This fix is available in the v4.0.0, that was just release: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/v4.0.0/CHANGELOG.md
