### ISSUE TITLE
Link to xmpp room

### ISSUE THREAD

**Issue by b4zz4** [JohnXLivingston/peertube-plugin-livechat#67]
A link to open an external app for chats, for example:

xmpp:{{ROOM}}?join

when the user puts the lives on a peertube

![](https://cdn.masto.host/mographsocial/media_attachments/files/106/750/097/927/179/095/original/ad34fb04aa4c603d.jpg)

**Comment by JohnXLivingston** [comment]
Can you be more specific on your request?
For which plugin's mode do you want this solution? (builtin Prosody ? others?)

How does it work from a technical point of view? Is the iframe on the current server, and the backend Prosody server will connect to a remote xmpp room in s2s mode ?

Have you some use cases? Can you share them?

**Comment by b4zz4** [comment]
From the server configuration you open the room for xmpp so you have the link for mobiles and other devices that are not using the browser, for emitters with low compute capacity or bad networks

**Comment by JohnXLivingston** [comment]
Oh ok. thanks for the clarification, I hadn't understood it like that at all.
This is already on my roadmap: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/ROADMAP.md , «Add a settings to enable the server to be accessed with XMPP clients.».

It is a little bit more complicated than just adding a link. I have to safely configure the Prosody server to open to the outer world (for now, Prosody only listen on localhost, and only the Peertube server can access it). I have to deal with several Peertube installation scheme (standard, docker, ...), and document each of them.

I also have to deal with certificates. On a standard installation I can import the nginx certificates, but I have to handle more specific cases (docker installations, nginx not on the same server, non standard installation paths, ...). Or, if this is not possible, generate self signed certificates.

Anyway, I have to do some R&D. And for now, I don't have any funding for working on this. For the record, I estimated this development at 1000€. If you have any financing leads, I'm interested.

I'm closing this issue, as it is already planned.

**Comment by b4zz4** [comment]
I'm sorry, but on the server I try this you can count from the outside and I thought you'd be.
Think it as a design for the roadmap.

**Comment by JohnXLivingston** [comment]
I'm not sure to understand what you just said. What do you mean by «count»?

For now, the Prosody configuration looks like:

```config
interfaces = {
  "127.0.0.1";
  "::1";
};
c2s_ports = {
};
c2s_interfaces = {
  "127.0.0.1";
  "::1";
};
s2s_ports = {
};
s2s_interfaces = {
  "127.0.0.1";
  "::1";
};
http_ports = {
  "52800";
};
http_interfaces = {
  "127.0.0.1";
  "::1";
};
https_ports = {
};
https_interfaces = {
  "127.0.0.1";
  "::1";
};
trusted_proxies = {
  "127.0.0.1";
  "::1";
};
```

So you can't connect from a non local IP. Except through the BOSH protocol. If your client supports BOSH, and somehow discover the BOSH url, it should be able to connect. I did not try this. But as it is not compatible with all xmpp client, I can't expose this method.
