### ISSUE TITLE
Docker image with specific PeerTube tag

### ISSUE THREAD

**Issue by kimsible** [JohnXLivingston/peertube-plugin-livechat#68]
**Is your feature request related to a problem? Please describe.**
When using the docker image `johnxlivingston/peertubelivechat` the last PeerTube release is not re-build, I get the v3.2.0.

**Describe the solution you'd like**
Using an image for each release with tags: `v3.3.0-buster`, `v3.4.0-buster`...

**Describe alternatives you've considered**
Maybe re-building the docker image for each PeerTube release.

**Comment by JohnXLivingston** [comment]
Hum... I definitively don't understand how docker works... (I don't use this software at all).

My image does just:
https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/e19420de6358f5dd43629dc96290545a88712115/docker/Dockerfile.buster#L1-L3

When I  browse @Chocobozzz 's docker repo, I can see that chocobozzz/peertube:production-buster
 was updated 4 days ago to the latest peertube version: https://hub.docker.com/layers/chocobozzz/peertube/production-buster/images/sha256-f6154761c845eb03a49b44e0b9e111e8f14b57c565adb791864905892dff5853?context=explore

So why does it not work? What have I to do?!

**Comment by kimsible** [comment]
I think `FROM chocobozzz/peertube:production-buster` is ran during the build only.

Your image has been built 3 months ago and 3 months ago `v3.3.0` and `v3.4.0` were not released yet, so `chocobozzz/peertube:production-buster` had `v3.2.0` release and will still have it until you re-build it each time a `chocobozzz/peertube` has a new release.

 The better way would be to have a proper image without PeerTube and editing the official Docker-Compose setup.

**Comment by kimsible** [comment]
You could use the official https://github.com/prosody/prosody-docker and adding a service in `docker-compose.yml`

**Comment by JohnXLivingston** [comment]
> You could use the official https://github.com/prosody/prosody-docker and adding a service in `docker-compose.yml`

I can't. Prosody must be in the same container as Peertube, because Peertube handle the prosody process and its configuration files. My plugin was build so, for standard installation, without Docker, and without conflicting with an existing Prosody installation. I made this docker image because it was requested.

**Comment by JohnXLivingston** [comment]
> I think `FROM chocobozzz/peertube:production-buster` is ran during the build only.
> 
> Your image has been built 3 months ago and 3 months ago `v3.3.0` and `v3.4.0` were not released yet, so `chocobozzz/peertube:production-buster` had `v3.2.0` release and will still have it until you re-build it each time a `chocobozzz/peertube` has a new release.
> 
> The better way would be to have a proper image without PeerTube and editing the official Docker-Compose setup.

Is there a way to rebuild an image, without installing Docker? I don't have Docker on my dev computer. And I prefer not to install it, if I can avoid to.

**Comment by JohnXLivingston** [comment]
Last time I used the automated build from github... But now you have to pay docker to have this feature...

**Comment by JohnXLivingston** [comment]
Ok, I think I found how to do.

**Comment by JohnXLivingston** [comment]
Can you please try with the image «johnxlivingston/peertubelivechat:v3.4.0-buster»?
If it works, i will update the existing tag.

**Comment by JohnXLivingston** [comment]
i also pushed the new image on the old tag (production-buster). I'm closing this issue. If it does not work please re-open it.

For future peertube release, i will build images and tag them as «vX.X.X-buster» and «production-buster».

Thanks for the report.

**Comment by kimsible** [comment]
Thanks for the support of these images !

For the docker support, it's not really optimal to put prosody in the PeerTube container, even I think it's a bad practice.
Maybe we could use the plugin and use an external prosody with ? (this should be the right way to not touch the official PeerTube repository)

**Comment by JohnXLivingston** [comment]
There are strong interaction with the builin prosody and the peertube server. Peertube must be able to change prosody configuration, restart prosody, communicate with, ...
It would be very difficult, and implies a lot of work and testing. 
Moreover, Peertube acts as a proxy to prosody (all web requests go through Peertube). So for me, it make sense to be in the same container.

**Comment by JohnXLivingston** [comment]
Hello @kimsible . I just realized I forgot to renew the image for Peertube 3.4.1.
I just made it.
https://hub.docker.com/r/johnxlivingston/peertubelivechat/tags
Can you please test it, and confirm that it is working? I'm not really comfortable with the docker building system...
Thanks a lot.

**Comment by kimsible** [comment]
Thank you so much John, I've totally forgot that patch !

**Comment by kimsible** [comment]
Hi @JohnXLivingston, PeerTube seems to stay to 3.4.0 in your last tag created for 3.4.1.

**Comment by JohnXLivingston** [comment]
Sorry for that @kimsible. I'm really bad with docker... And I have no more server where I can test docker builds. 
Should be fixed now.

**Comment by JohnXLivingston** [comment]
Hello @kimsible . I just updated docker images to provide peertube v4.1.0. Can you test?
Important note: there is no more Debian Buster image, you have to use production-bullseye or v4.1.0-bullseye. See: https://hub.docker.com/r/johnxlivingston/peertubelivechat/tags
