### ISSUE TITLE
Cannot re-install plugin after uninstalled it

### ISSUE THREAD

**Issue by kimsible** [JohnXLivingston/peertube-plugin-livechat#69]
**To Reproduce**
1. Install the plugin
2. Set the xmpp server as prosody
3. Uninstall the plugin

```
error[9/14/2021, 2:12:47 PM] Cannot install plugin peertube-plugin-livechat, removing it...

{
  "err": {
    "stack": "Error: spawn prosodyctl ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)\n    at onErrorNT (internal/child_process.js:470:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
    "message": "spawn prosodyctl ENOENT",
    "errno": "ENOENT",
    "code": "ENOENT",
    "syscall": "spawn prosodyctl",
    "path": "prosodyctl",
    "spawnargs": [
      "--config",
      "/data/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua",
      "status"
    ]
  }
}

warn[9/14/2021, 2:12:47 PM] Cannot unregister plugin peertube-plugin-livechat.

{
  "err": {
    "stack": "Error: Unknown plugin peertube-plugin-livechat to unregister\n    at PluginManager.<anonymous> (/app/dist/server/lib/plugins/plugin-manager.js:181:23)\n    at Generator.next (<anonymous>)\n    at /app/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/app/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.unregister (/app/dist/server/lib/plugins/plugin-manager.js:177:24)\n    at PluginManager.<anonymous> (/app/dist/server/lib/plugins/plugin-manager.js:261:28)\n    at Generator.next (<anonymous>)\n    at /app/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/app/node_modules/tslib/tslib.js:113:16)\n    at PluginManager.uninstall (/app/dist/server/lib/plugins/plugin-manager.js:258:24)\n    at PluginManager.<anonymous> (/app/dist/server/lib/plugins/plugin-manager.js:228:32)\n    at Generator.throw (<anonymous>)\n    at rejected (/app/node_modules/tslib/tslib.js:115:69)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "message": "Unknown plugin peertube-plugin-livechat to unregister"
  }
}
```

**Server (please complete the following information):**
 - Peertube version: v3.3.0
 - Peertube installation type: docker
 - peertube-plugin-livechat version: 4.0.0

**Comment by JohnXLivingston** [comment]
I thinks it is a Peertube's bug. Can you try to restart peertube, and see if it works?

**Comment by JohnXLivingston** [comment]
Are you using my docker image?

**Comment by kimsible** [comment]
No, it's the production server QueerMotion, we have no plan to upgrade PeerTube this week, maybe the next week, so we are still on v3.3.0 official image.

It could be linked to your `register` function in the plugin: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/e19420de6358f5dd43629dc96290545a88712115/server/main.ts#L12

**Comment by JohnXLivingston** [comment]
Ok, I think I got it. Just a moment...

**Comment by JohnXLivingston** [comment]
In your docker compose file, use `johnxlivingston/peertubelivechat:v3.3.0-buster` instead of `johnxlivingston/peertubelivechat:production-buster`, as documented here:
https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md#for-docker-installations

**Comment by JohnXLivingston** [comment]
> No, it's the production server QueerMotion, we have no plan to upgrade PeerTube this week, maybe the next week, so we are still on v3.3.0 official image.
> 
> It could be linked to your `register` function in the plugin:
> 
> https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/e19420de6358f5dd43629dc96290545a88712115/server/main.ts#L12

I think there is a missing `try {} catch() {} ` somewhere. I will check that later today.

**Comment by JohnXLivingston** [comment]
Should be fixed with https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/543e454b512271ca253266d818708a40ff958f11
(it is not the smartest fix, but it should do the job).

I'm going to release the plugin in a few minutes. To make it available quicker (without waiting plugin indexing), you can change the column PluginLatestVersion in the plugin table to 4.0.1.

**Comment by kimsible** [comment]
Thank you so much for the quick support :heart:
The `johnxlivingston/peertubelivechat:v3.3.0-buster` seems to work as great as the last fix of the plugin =)

**Comment by JohnXLivingston** [comment]
My pleasure! I love to hear that my plugin is used :)
