### ISSUE TITLE
Feature Request: message approval

### ISSUE THREAD

**Issue by EkkiBrue** [JohnXLivingston/peertube-plugin-livechat#80]
Probably I´m blind and / or I can´t find the settings for it. So sorry if this has been asked before.

Is it possible by a moderator to approve individual posts in the chat before publishing them ?

**Comment by JohnXLivingston** [comment]
Are you using the builtin prosody mode?

I don't think you can do this. But you can set the room in moderated mode:

- open the chatroom in fullscreen
- use the top right menu to open the «configure» form

![image](https://user-images.githubusercontent.com/38844060/145838856-82d84d06-137e-4c33-bb3d-0e273fa9e23e.png)

- Check the setting «Moderated (require permission to speak)»

Then only authorized users can speak. 
To grant the right to speak to non-moderators: type «/voice the_user_nickname».
To remove the right: «/mute the_user_nickname».

Note: you can also mute a user, event if the room is not moderated (with the /mute command).

More information in the ConverseJS documentation: https://conversejs.org/docs/html/features.html#moderating-chatrooms

**Comment by EkkiBrue** [comment]
Hi John.

Thank you very much for your time an effort. I am aware of these settings - and the plugin itself works perfcect so far!  So I´m kindly asking for a feature request here.

We are working in an educational settings and we´d like to moderate upfront before posting a chat message to the whole channel. We know we can moderate AFTER a post was made - kick user or delete a message - but it would be a blast if this moderation could take place BEFORE letting the post through... I hope you understand what I mean. And this is not exactly about censorship - but it´s about teaching kids in different roles to be moderated and to be the moderator. Would help us a lot here - also in Live-Streaming Setups...

Thank you again for your time and effort to make this plugon happen!!!

All the best

**Comment by JohnXLivingston** [comment]
Ok, I see. I don't know if there is such a feature with XMPP. I can't find anything.

I know that this issue tracker is followed by https://github.com/jcbrand , who is a ConverseJS dev. JC, if you see this message, do you know if there is a XMPP extention for that?

PS: great to ear that your are using this plugin for educational purpose :)

**Comment by jcbrand** [comment]
Sorry, I'm not aware of such a feature for XMPP.

The tricky part would be to route the messages to moderators and then to let them approve/deny the messages. Could be an interesting XEP and project to work on, but won't be trivial to design or implement.

**Comment by JohnXLivingston** [comment]
> Sorry, I'm not aware of such a feature for XMPP.
> 
> The tricky part would be to route the messages to moderators and then to let them approve/deny the messages. Could be an interesting XEP and project to work on, but won't be trivial to design or implement.

That's what I thought. 
@EkkiBrue , sorry. I will let this issue open, in case someone came with a solution.

@jcbrand , thanks for your respond. I'm curious: are you following this repo because you are using Peertube? Or just because it uses ConverseJS?
And thanks for your work on ConverseJS, it is really a great software!

**Comment by EkkiBrue** [comment]
@JohnXLivingston & @jcbrand 
I really appreciate this. That would be great if that could be realized at some point. Thanks alot, dudes! ;)

**Comment by jcbrand** [comment]
@JohnXLivingston: I like to keep an eye on projects that use Converse so that I can help out if possible.

I don't currently host Peertube myself, but I think it's a great project

**Comment by JohnXLivingston** [comment]
I'm closing this issue (I'm cleaning issues for better project followup). 

There will be work on moderation tools in 2023. This exact feature is not planned, but I think there will be acceptable solutions (more information to come soon).
