### ISSUE TITLE
Testing Chat in IFRAME

### ISSUE THREAD

**Issue by EkkiBrue** [JohnXLivingston/peertube-plugin-livechat#81]
Hi again.

Sorry to bother you again but I´m in heavy testing mood. ;)

I try to integrate a peertube video in an IFRAME with an additional Chat-Window in another IFRAME on the same site.

The Wordpress Code how we integrate this into our site looks like this:

```
<iframe title="test" src="https://video.xxxxxxxxxxxxxxxxxx.de/videos/embed/6dsfv-4cc0-b089-8e6f16b6233ctitle=0&amp;warningTitle=0&amp;controls=1&amp;peertubeLink=0" width="1280" height="720" frameborder="0" sandbox="allow-same-origin allow-scripts allow-popups" allowfullscreen="allowfullscreen"></iframe>

<iframe src="https://video.xxxxxxxxxxxxxxxxxx.de/plugins/livechat/5.0.2/router/webchat/room/6dsfv-4cc0-b089-8e6f16b6233c" width="100%" height="720" frameborder="0" sandbox="allow-same-origin allow-scripts allow-popups" allowfullscreen="allowfullscreen"></iframe>
```

The site we integrate this is here so you can reproduce the following behaviour:
xxxxed for safety reason

Problem:
With the upper setup in two IFRAMES we are unable to join as a new user to the chat.
If we run the chat on the link itself (withour IFRAME) in a solo browser tab it works and new users can register.
Are we doing something wrong ?

![image](https://user-images.githubusercontent.com/6376844/146002987-8c2fe3ab-741e-46bc-8042-08611a07e0a2.png)

Inserting a name and pressing the button "Gruppenchat beitreten" does nothing in IFRAME Mode.

Hope I have made myself clear ;)

Thank you!

**Comment by JohnXLivingston** [comment]
Try to add `allow-forms` in the sandbox attribute.

For the record, I'm currently working on something that could interest you... A «share url» button, to share and customize the webchat! It is meant to be used as an OBS overlay for streamers, but it could totally be used to generate iframes. I'll add this case! 
It will be included in the next release (probably this week).

**Comment by EkkiBrue** [comment]
Works like a charm! ;) Sorry to bother you with simple questions like this... Could just have thought this through at the first place...

OBS would be a blast to be integrated. We are using this in our environment a lot and it would fit our needs perfectly... Thanks for sharing this...

**Comment by JohnXLivingston** [comment]
> Works like a charm! ;) Sorry to bother you with simple questions like this... Could just have thought this through at the first place...

Nice!

> OBS would be a blast to be integrated. We are using this in our environment a lot and it would fit our needs perfectly... Thanks for sharing this...

Here is a link to a pre-alpha of what I'm doing: https://videos.john-livingston.fr/w/qqNQwFDerUB1KnFA6N6Jbi
On top of the chat, there is a new button «share chat link». When you click, it opens a modal.
For now there is only one question in the modal (readonly or not?). But i'll add some more (iframe? colors to use? ...)
This generates a link to share the chat.

If you check «readonly», you have access to a brand new mode (available in next release). This link can be used in OBS!
Check the result here: https://videos.john-livingston.fr/plugins/livechat/5.0.2/router/webchat/room/c5d20adf-1088-4d40-bbfc-1abb42d20b05?_readonly=true

These features are brand new. I started today! Should be released this week :)

**Comment by EkkiBrue** [comment]
Sweet one! I´ll be happy to check it the next day when we have a OBS Session. We also use OBS Ninja now - let´s see how all this integrates...

Probably you have time for another short question: 
is there a way to set the basic colours of the chat window in CSS somewhere ? I tried to alter e.g. the css for

#conversejs .chatroom .send-button {
    background-color: #C63663;
}

in peertube configuration / advanced to change the  default orange to our main-color. It didn´t reflect my changes (and logically it should´nt because the iframe relies on the css of converse.js I gues..)

Also I´d like to change the peertube logo on start.

If there is a chance to implement the basic colour changes in the plugin and to have a chance to replace the main logo would be very nice... Would suit the look and feel of the site a lot...

Thanks again for your kind help.... - Watched some card-tricks ;)

**Comment by JohnXLivingston** [comment]
I had already been asked for this type of customization. 
I haven't done it yet, because I don't want to shoot myself in the foot by making future developments more complicated.

Also, I've used up the funding I received to work on the plugin. If you have a budget to spend on it, we can definitely see what is possible. Otherwise, i unfortunately have other priorities.

Note: with the tool I'will release this week, you will be able to change colors.

**Comment by JohnXLivingston** [comment]
And by the way, thanks for the tip on paypal :)

**Comment by EkkiBrue** [comment]
You are welcome - yes and I know it´s nothing more than a tip ;)
My organisation is a public insitution and still there are MANY bureaucratic hurdles to jump over to support open source projects on a larger scale. So my and our only chance here is to support projects privately - and this can only be ment as a symbolic support for all your hard work. So thanks again... 

We are still fighting for a political change to support "public money, public code" ;) Hope we will be there one day.

**Comment by JohnXLivingston** [comment]
It always hurts my heart to have to answer like that, but unfortunately I have to... My freelance activity doesn't bring me enough money to live on yet. Thanks again for the support and for the interest in this project.
