### ISSUE TITLE
Update the title of the chat when the title of the stream changes

### ISSUE THREAD

**Issue by Booteille** [JohnXLivingston/peertube-plugin-livechat#87]
**Is your feature request related to a problem? Please describe.**
I just updated the name of my recurrent live stream and the tchat title didn't update.

**Describe the solution you'd like**
It would be neat if the title of the chat windows would change when we update the stream title.

Reference: NlNet-task-20

**Comment by JohnXLivingston** [comment]
Will be fixed in next release!
