### ISSUE TITLE
Lost connection to chat

### ISSUE THREAD

**Issue by Alterak** [JohnXLivingston/peertube-plugin-livechat#88]
Chat Version 5.4.0
Peertube version 4.0.0
Server address [peervideo.ru ](https://peervideo.ru/)

The problem appeared about 2 weeks ago, in the latest versions of the chat. If I start the stream, then the chat is active ... I hide on the panel. After about 30 minutes, the chat is inactive, I have to refresh my stream page. I have attached screenshots below with logs.

Chat works well here.
![Screenshot_1](https://user-images.githubusercontent.com/11453567/149632951-f1054790-1155-494b-b21c-2190e3dd4af2.png)

Here the chat is inactive after about 30 minutes
![Screenshot_2](https://user-images.githubusercontent.com/11453567/149632959-bda2fbbf-5cc3-466e-99bb-c60ee6ac7df2.png)

**Comment by Alterak** [comment]
Such a problem in the last two versions. I really hope you fix this.

**Comment by JohnXLivingston** [comment]
Thanks for the report. I think the problem is related to the ConverseJS version change (I updated the library from version 7.0.6 to 9.0.0).
I will investigate this in the coming days.

**Comment by JohnXLivingston** [comment]
I just tested on firefox. I was not able to reproduce. I waited 33 minutes with the tab in the background.

If you can, can you try with firefox (I see in the screenshot you are using chrome).

I'll search for the error messages in the ConverseJS code (but not today, I have other tasks to achieve).

**Comment by Alterak** [comment]
I tested on 3 browsers

Firefox - works good.
Google Chrome - the connection is terminated.
Microsoft EDGE - the connection is terminated.

**Comment by JohnXLivingston** [comment]
Ok thanks, that helps.
Was the browser tab in the background? Or always displayed?

**Comment by JohnXLivingston** [comment]
I think it may be related to https://github.com/conversejs/converse.js/issues/2770
