### ISSUE TITLE
XMPP support chat not working

### ISSUE THREAD

**Issue by Porrumentzio** [JohnXLivingston/peertube-plugin-livechat#9]
Seems tha the server room.im.yiny.org is not working

**Comment by JohnXLivingston** [comment]
Can you be more specific? What is not working? You can't join the support room? This server is not open to registration, you have to create a Jabber account on another server to join the room.

**Comment by Porrumentzio** [comment]
I can not join into it on any client, with already existing XMPP account on other server

The error messages say that the _server is not working_ or _server timeout_

**Comment by JohnXLivingston** [comment]
I just tried with an account on jabber.fr with the «conversation» client, and it worked. What is your server url? (so that I can search in my log files if there is an error). Does your server allow remote rooms?

**Comment by Porrumentzio** [comment]
It's disroot.org
Yes, I can join on other servers' rooms.

**Comment by JohnXLivingston** [comment]
I see nothing like «disroot» in my server logs. I just created a disroot account, I have to wait the validation to try by myself.

**Comment by Porrumentzio** [comment]
Maybe the room's name is not correctly wrote on on the readme?
It is this,
xmpp:plugin-livechat-support@room.im.yiny.org?join

Right?

**Comment by JohnXLivingston** [comment]
> Maybe the room's name is not correctly wrote on on the readme?
> It is this,
> xmpp:[plugin-livechat-support@room.im.yiny.org](mailto:plugin-livechat-support@room.im.yiny.org)?join

Oh, github automatically added a «mailto:». You can copy the room addresse and paste it in your client. I'm going to fix the README.

**Comment by JohnXLivingston** [comment]
Hum, it seems github fails with XMPP links... https://github.com/github/markup/issues/1436

**Comment by Porrumentzio** [comment]
Doing what you say, I enter on an empty room that is not working properly and forces me to leave

**Comment by JohnXLivingston** [comment]
What client are you using? The disroot web client ? Or a desktop client like Gajim?

**Comment by Porrumentzio** [comment]
Blabber on Android and Dino in computer. Gajim also answers "remote server timeout"

**Comment by JohnXLivingston** [comment]
That's weird. It work for me with Gajim on my computer, and Conversation on my mobile. Did you remove the «mailto» that github added? Are you using the «join a room» feature? (not «add a contact»)

**Comment by Porrumentzio** [comment]
Yes, even searching for that room and entering gives that error

**Comment by JohnXLivingston** [comment]
Ok, I see an error log from disroot now. I'm investigating.

**Comment by JohnXLivingston** [comment]
Is it working now?
