### ISSUE TITLE
Getting "the group chat does not (yet) exist"

### ISSUE THREAD

**Issue by jimgroom** [JohnXLivingston/peertube-plugin-livechat#90]
**Describe the bug**
The chat does not load I just get the message "the group chat does not (yet) exist"

**To Reproduce**
1. Go to 'Live Video'
from public browser not logged in
2. See error
3. When logged in I just see a blank chat screen

**Expected behavior**
The ability to chat on a live video

**Server (please complete the following information):**
Docker Buster edition loaded based on the livechat version specified through this account
 - Peertube version: 3.4.1
 - Peertube installation type [e.g. standard, docker, ...]:  Docker
 - peertube-plugin-livechat version: 5.4.0
 - Chat mode if relevant: Prodody

**Plugin diagnostic:**
If this is a server setup issue, please go to the plugin settings, click on «launch diagnostic», and copy/paste the result.
Diagnostic
Starting tests: OK
Browser: OK
Backend connection: OK
Webchat activated on videos: OK
Chat will open automatically
Displaying «open in new window» button
Chat can be enabled on live videos.
Chat is enabled for all lives.
Webchat type: OK
Using builtin Prosody
Builtin Prosody and ConverseJS: KO
The working dir is: /data/plugins/data/peertube-plugin-livechat/prosody
Prosody will run on port '52800'
Prosody will use https://bava.tv/plugins/livechat/5.4.0/router/api/ as base uri from api calls
Prosody modules path will be '/data/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules'
Prosody rooms will be grouped by 'channel'.
By default, room content will be archived.
Room content will be saved for 'never'
The prosody configuration file (/data/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
Prosody configuration file content is correct.
Pid file /data/plugins/data/peertube-plugin-livechat/prosody/prosody.pid found
Prosodyctl status: Prosody is running with PID 53
The prosody configuration file (/data/plugins/data/peertube-plugin-livechat/prosody/prosody.cfg.lua) exists
Prosody configuration file content is correct.
Prosody version is 0.11.2
API Peertube -> Prosody is OK
API Prosody -> Peertube is KO. Response was: {"ok":false,"error":"Rejected by API"}
Additional debugging information
Current prosody configuration
daemonize = false;
allow_registration = false;
admins = {
};
pidfile = "/data/plugins/data/peertube-plugin-livechat/prosody/prosody.pid";
plugin_paths = {
  "/data/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules";
};
data_path = "/data/plugins/data/peertube-plugin-livechat/prosody/data";
default_storage = "internal";
storage = "internal";
modules_enabled = {
  "roster";
  "saslauth";
  "carbons";
  "version";
  "uptime";
  "ping";
  "bosh";
  "posix";
};
modules_disabled = {
  "s2s";
};
cross_domain_bosh = false;
consider_bosh_secure = true;
cross_domain_websocket = false;
consider_websocket_secure = false;
c2s_require_encryption = false;
interfaces = {
  "127.0.0.1";
  "::1";
};
c2s_ports = {
};
c2s_interfaces = {
  "127.0.0.1";
  "::1";
};
s2s_ports = {
};
s2s_interfaces = {
  "127.0.0.1";
  "::1";
};
http_ports = {
  "52800";
};
http_interfaces = {
  "127.0.0.1";
  "::1";
};
https_ports = {
};
https_interfaces = {
  "127.0.0.1";
  "::1";
};
log = {
  info = "/data/plugins/data/peertube-plugin-livechat/prosody/prosody.log";
  error = "/data/plugins/data/peertube-plugin-livechat/prosody/prosody.err";

};

VirtualHost "bava.tv"
  authentication = "http";
  modules_enabled = {
  "ping";
  "auth_http";
  "http";
  "bosh";
  "vcard_peertubelivechat";
};
  http_auth_url = "https://bava.tv/plugins/livechat/5.4.0/router/api/user";
  trusted_proxies = {
  "127.0.0.1";
  "::1";
};
  allow_anonymous_s2s = false;
  http_host = "bava.tv";
  http_external_url = "http://bava.tv";
  peertubelivechat_vcard_peertube_url = "https://bava.tv";

VirtualHost "anon.bava.tv"
  authentication = "anonymous";
  modules_enabled = {
  "ping";
  "http";
  "bosh";
  "random_vcard_peertubelivechat";
};
  trusted_proxies = {
  "127.0.0.1";
  "::1";
};
  allow_anonymous_s2s = false;
  http_host = "bava.tv";
  http_external_url = "http://bava.tv";
  peertubelivechat_random_vcard_avatars_path = "/data/plugins/node_modules/peertube-plugin-livechat/dist/server/avatars";

Component "room.bava.tv" "muc"
  muc_room_locking = false;
  muc_tombstones = false;
  muc_room_default_language = "en";
  muc_room_default_public = false;
  muc_room_default_persistent = true;
  muc_room_default_members_only = false;
  muc_room_default_moderated = false;
  muc_room_default_public_jids = false;
  muc_room_default_change_subject = false;
  muc_room_default_history_length = 20;
  restrict_room_creation = false;
  http_host = "bava.tv";
  http_external_url = "http://bava.tv";
  modules_enabled = {
  "muc_http_defaults";
  "muc_mam";
  "muc_moderation";
  "http_peertubelivechat_list_rooms";
  "http_peertubelivechat_test";
};
  muc_create_api_url = {
  "https://bava.tv/plugins/livechat/5.4.0/router/api/room?apikey=***APIKey***&jid={room.jid|jid_node}";
};
  muc_log_by_default = true;
  muc_log_presences = true;
  log_all_rooms = false;
  muc_log_expires_after = "never";
  muc_log_cleanup_interval = 14400;
  peertubelivechat_list_rooms_apikey = "***APIKey***";
  peertubelivechat_test_apikey = "***APIKey***";
  peertubelivechat_test_peertube_api_url = "https://bava.tv/plugins/livechat/5.4.0/router/api/test?apikey=***APIKey***";

Prosody version
Prosody 0.11.2

# Prosody directories
Data directory:     /data/plugins/data/peertube-plugin-livechat/prosody/data
Config directory:   /etc/prosody
Source directory:   /usr/lib/prosody
Plugin directories:
  /data/plugins/node_modules/peertube-plugin-livechat/dist/server/prosody-modules
  /usr/lib/prosody/modules/
  

# Lua environment
Lua version:             	Lua 5.2

Lua module search paths:
  /usr/lib/prosody/?.lua
  /usr/local/share/lua/5.2/?.lua
  /usr/local/share/lua/5.2/?/init.lua
  /usr/local/lib/lua/5.2/?.lua
  /usr/local/lib/lua/5.2/?/init.lua
  /usr/share/lua/5.2/?.lua
  /usr/share/lua/5.2/?/init.lua

Lua C module search paths:
  /usr/lib/prosody/?.so
  /usr/local/lib/lua/5.2/?.so
  /usr/lib/x86_64-linux-gnu/lua/5.2/?.so
  /usr/lib/lua/5.2/?.so
  /usr/local/lib/lua/5.2/loadall.so

LuaRocks:        	Not installed

# Lua module versions
lfs:     	LuaFileSystem 1.6.3
libevent:	2.1.8-stable
luaevent:	0.4.6
lxp:     	LuaExpat 1.3.0
socket:  	LuaSocket 3.0-rc1
ssl:     	0.7

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser  Chrome and Safari

**Additional context**
Love this plugin and happy to help write documentation

**Comment by JohnXLivingston** [comment]
Hello,

In the plugin settings, can you try to set the value for the field «Peertube url for API calls» to «http://localhost:9000» (assuming that Peertube use the port 9000 in its configuration file, which is the default). If it does not work, try http://127.0.0.1:9000

![image](https://user-images.githubusercontent.com/38844060/149938273-ba416e2a-f13a-477f-aae4-e2e630171afc.png)

**Comment by jimgroom** [comment]
John,

That fixed it, thanks for the asesome plugin and let me know if you need help with documentation

**Comment by JohnXLivingston** [comment]
Thanks!

The bug you had is something many users have. I don't understand why. I should definitively try to detect this bug, and show a message somewhere (at top of the diagnostic tool for example). 

For the documentation, I will rewrite it in the next weeks. It will be a complete website, with a user documentation, admin documentation, moderation documentation, FAQ, search engine, ...
But first, I have to do some work to simplify the plugin. Probably split it in 3: one plugin per «chat mode» (see the first settings).
These modes are here for historical reason and backward compatibility. But it makes it complicated to explain for new users, and make the code hard to maintain and evolve. 
There are a lot of thinking on this subject (with a french group of persons).

Anyway, thanks a lot for your compliment, and your proposal.
